baseURL = "/"
languageCode = "en-us"
title = "NateDay-ta"
description = "R focused data docs"
theme = "minimal"
disqusShortname = ""#"nateday-me" # delete this to disable disqus comments
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Nate Day"
    description = "R focused data docs"
    githubUsername = "NathanCDay"
    accent = "darkblue"
    showBorder = true
    backgroundColor = "#f5f5f5"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "tomorrow-night-blue"
    highlightLanguages = ["R"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3
    
[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:nathancday@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/NathanCDay"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/offallday/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/nathan-day-59b48435/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/5878751/nate"
    name = "stack-overflow"
    weight = 5
