---
title: 'Data Deep Dive: Drug Crime in Cville'
author: Nate Day
date: '2018-02-07'
slug: data-deep-dive-drug-crime-in-cville
categories:
  - Cville Open Data
tags:
  - sf
  - tidyverse
  - api
---

* [ioSlides ready to view in your browser](https://natedayta.com/slides/crime_deep_dive/crime_deep_dive.html)
* [Code-along templates and source code to reproduce everything on GitHub](https://github.com/NathanCDay/data_dive)

This talk was part of [Smart Cville's Data Deep Dive](https://www.smartcville.com/) series focusing on Charlottesville City's new [Open Data Portal](http://opendata.charlottesville.org/).

The goals of this talk were to introduce the new `library(sf)` for spatial data manipulation and provide a tidyverse-centric template for other data analysts to use for exploring the public Charlottesville Police Department records. I built some code-along templates to make the talk less boring and more interactive, and those are in a [public GitHub repo here](https://github.com/NathanCDay/data_dive). If you want to revisit the slides I presented at the event, they are [hosted here on this site](https://natedayta.com/slides/crime_deep_dive.html).

Also since this project required some development version packages, which can be messy to install, Jeff Xing kindly [built a Docker image](https://hub.docker.com/r/jfx319/datadive/) that runs RStudio server and has all of the required libraries ready to go.