---
title: 'Endangered Data Week: Parking Meters'
author: Nate Day
date: '2018-02-25'
slug: endangered-data-week-parking-meters
categories:
  - Cville Open Data
  - R
  - EDA
tags:
  - tidyverse
  - lubridate
  - ggplot2
  - leaflet
---

* [ioSlides ready to view in your browser](https://natedayta.com/slides/parking_meters/parking_meters.html)
* [Github repo with all of my code](https://github.com/nathancday/)

This talk is meant to be a short example of how data analysis can help make better decisions for the city of Charlottesville. It shows data from the canceled Downtown mall parking meter pilot study, which the city council voted to discontinue in January, causing the city to loss money on the project. This exploratory data anlysis show how much revenue the city was generating and when the meters were being utilized. Business owners feared the meters would hurt their bottom lines with less patron traffic and harder employee parking accomedations, but the data shows steady usage across the study, with the expected spikes in activity around lunch, dinner and on the weekends.
